### ISSUE TITLE
启动API报错

### ISSUE THREAD

**Issue by GuoxinL** [Guo-Chenxu/go-zero-demo#1]
![image](https://github.com/Guo-Chenxu/go-zero-demo/assets/19989609/9ca0b758-6ef9-4145-afe6-d5fcc967b1f5)
下载您的demo启动nacos启动api报错，请问有遇到过这个问题吗

**Comment by Guo-Chenxu** [comment]
> ![image](https://private-user-images.githubusercontent.com/19989609/288008864-9ca0b758-6ef9-4145-afe6-d5fcc967b1f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzMwNzgsIm5iZiI6MTcwMTc3Mjc3OCwicGF0aCI6Ii8xOTk4OTYwOS8yODgwMDg4NjQtOWNhMGI3NTgtNmVmOS00MTQ1LWFmZTYtZDVmY2M5NjdiMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEwMzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNDRjMzMxY2U2MmMzYmE4OGIzN2YxNWRhZDc3OWYyMWUwMWZlZDJjYjgwYTM2Njc4YzFiZGZkZTAzZWE1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.maBarmGB2l6tte8sCklZ4NeVOGxGjPEOaLrlObEAE2E) 下载您的demo启动nacos启动api报错，请问有遇到过这个问题吗

你好, 这是因为启动`api`的时候找不到`rpc`服务, 要先启动`rpc`成功后再启动`api`

**Comment by GuoxinL** [comment]
rpc服务已经启动了呀

**Comment by GuoxinL** [comment]
> ![图像](https://private-user-images.githubusercontent.com/19989609/288008864-9ca0b758-6ef9-4145-afe6-d5fcc967b1f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzQ1MzEsIm5iZiI6MTcwMTc3NDIzMSwicGF0aCI6Ii8xOTk4OTYwOS8yODgwMDg4NjQtOWNhMGI3NTgtNmVmOS00MTQ1LWFmZTYtZDVmY2M5NjdiMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExMDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGM2ZjYwMDFmZDg0MTUyMzgwZGZiOGQ3MzExOGMwYjdjZDAzZmRmZjNhOTQzYzU2ZTkzMTJiOGRkYjU3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wop_KATBT_IVYvepkbp_EcNc8l2P_-hwIDJ_dnZ6lys) 下载您的demo启动nacos启动api报错，请问遇到过这个问题吗？

我觉的解析的不对，因为报错中输出不止解析出来服务的名称还有?后面的内容

**Comment by Guo-Chenxu** [comment]
> rpc服务已经启动了呀

你看一下你的nacos注册中心里面能不能找到你的rpc服务, 检查一下`api`和`rpc`中nacos配置的ip host namespace是否一致

**Comment by Guo-Chenxu** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/19989609/288008864-9ca0b758-6ef9-4145-afe6-d5fcc967b1f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzQ1MzEsIm5iZiI6MTcwMTc3NDIzMSwicGF0aCI6Ii8xOTk4OTYwOS8yODgwMDg4NjQtOWNhMGI3NTgtNmVmOS00MTQ1LWFmZTYtZDVmY2M5NjdiMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExMDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGM2ZjYwMDFmZDg0MTUyMzgwZGZiOGQ3MzExOGMwYjdjZDAzZmRmZjNhOTQzYzU2ZTkzMTJiOGRkYjU3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wop_KATBT_IVYvepkbp_EcNc8l2P_-hwIDJ_dnZ6lys) 下载您的demo启动nacos启动api报错，请问遇到过这个问题吗？
> 
> 我觉的解析的不对，因为报错中输出不止解析出来服务的名称还有?后面的内容

`?` 后面也是配置参数, 分别是`超时时间`和`命名空间id`, 看样子你似乎没有配置`namespaceid`, 可以配置一下再试试

**Comment by GuoxinL** [comment]
![image](https://github.com/Guo-Chenxu/go-zero-demo/assets/19989609/ef9b58f8-84b5-46ed-b090-2a2cf624ec62)
是注册上去的

![image](https://github.com/Guo-Chenxu/go-zero-demo/assets/19989609/b4f9b1b7-f9c4-4096-944a-416e6ffe1c9f)

**Comment by Guo-Chenxu** [comment]
我刚才测试了一下demo, 一切正常, 能看一下你的配置文件吗? 并且我看到你是本地的nacos, 或许你可以将这张图里的`ip`改成`127.0.0.1`再试试🤔

![image](https://github.com/Guo-Chenxu/go-zero-demo/assets/90923304/d5f7ce2f-f8f1-4183-9802-d79f803a725b)

**Comment by GuoxinL** [comment]
有没有可能我用了没有用户名密码的nacos

**Comment by GuoxinL** [comment]
我换一个试试，非常感谢你能抽空回复😁

**Comment by Guo-Chenxu** [comment]
> 有没有可能我用了没有用户名密码的nacos

这个我记得应该是不影响的 (不过也说不准)

**Comment by Guo-Chenxu** [comment]
由于太长时间没有更新, 这个issue我先关了, 如果有问题可以随时reopen
